eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka
management:
    endpoints:
        web:
            exposure:
                include: health
server:
    port: 5555
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:

            -   id: users-ws
                uri: http://localhost:8080
                predicates:
                - Path=/smart/users
                - Method=POST
                filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/smart/(?<segment>.*), /${segment}

            -   id: users-ws-login
                uri: http://localhost:8080
                predicates:
                - Path=/auth/login
                - Method=POST
                filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/auth/(?<segment>.*), /users/${segment}


            -   id: users-ws-get-update-delete
                uri: http://localhost:8080
                predicates:
                - Path=/smart/users/**
                - Method=GET,PUT,DELETE,POST
                - Header=Authorization, Bearer (.*)
                filters:
                - RemoveRequestHeader=Cookie
                - AuthorizationHeaderFilter
                - RewritePath=/smart/(?<segment>.*), /${segment}

            -   id: post-ws-get-update-delete
                uri: http://localhost:8081
                predicates:
                - Path=/post/**
                - Method=GET,PUT,DELETE,POST
                filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/post/(?<segment>.*), /${segment}
                - AuthorizationHeaderFilter

            -   id: post-ws-actuator
                uri: http://localhost:8081
                predicates:
                - Path=/post/actuator/*
                - Method=GET
                filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/post/(?<segment>.*), /${segment}
                - AuthorizationHeaderFilter

token:
    secret: hfgry463hf746hf573ydh475fhy5739
