server:
  port: 5555

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-smart-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

#spring:
#  application:
#    name: gateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: baeldung
#          uri: baeldung.com
#        - id: myOtherRouting
#          uri: localhost:9999
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#          - "routes"